Working example of a DataTable for the dashboard
Champion-Devs/ZappNode pull request #20
Opened 2020-07-27 14:17 UTC by heyitschun

Added a working example of a `DataTable` component in `src/components/dashboard/DataTable.js`.
Fixed `DataView` to not render more rows that gets passed through.

Also removed unused icon declarations from `public/manifest.json`

2020-07-27 14:44 UTC, insuusvenerati commented
Added some reviewers. Check the comments and lemme know what you think. I'll pull this in and check it out soon.

2020-07-27 16:47 UTC, aorelhas submitted a review, later dismissed
For me, looks good.

2020-07-27 21:50 UTC, insuusvenerati requested changes

2020-07-27 21:50 UTC, insuusvenerati commented on zappnode-front/public/index.html
> -    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
This can actually stay in the event the app gets used as a PWA

2020-07-27 21:50 UTC, insuusvenerati commented on zappnode-front/src/service/TrackerService.js
> +    const res = await axios.get('data/track-data.json');
Do we really need axios for this? fetch will work just the same, except the response has to be converted to json. Maybe let's avoid an un needed dependency for now.

2020-07-27 22:25 UTC, insuusvenerati commented on zappnode-front/src/components/dashboard/DataTable.js
> +import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/nova-light/theme.css';
import 'primereact/resources/primereact.css';

2020-07-27 22:26 UTC, insuusvenerati commented on zappnode-front/package.json
> +    "axios": "^0.19.2",
```suggestion

```

2020-07-28 16:03 UTC, insuusvenerati approved these changes

2020-07-28 16:04 UTC, insuusvenerati commented
If this looks good to @aorelhas and @priyajitm then we can merge ;)

2020-07-28 16:13 UTC, priyajitm commented
Removing axios will increase performance, maybe for miliseconds but nonetheless it will.

2020-07-28 16:15 UTC, insuusvenerati commented
> Removing axios will increase performance, maybe for miliseconds but nonetheless it will.

Axios is just super powerful. It's great when you use it's features though. In this case a fetch was more than enough. We can even build custom hooks with fetch to extend it a bit.

2020-07-28 16:53 UTC, merged