BarChart and DataView components
Champion-Devs/ZappNode pull request #42
Opened 2020-07-30 15:28 UTC by heyitschun

2020-08-01 10:54 UTC, binismail reviewed
looks good

2020-08-01 17:17 UTC, insuusvenerati requested changes
This looks very good. Just needs some padding :)

2020-08-01 17:17 UTC, insuusvenerati commented on zappnode-front/src/routes/Dashboard.js
> +      <div className="mt-12">
Let's add some padding to these so they aren't sitting on the edges. 

```suggestion
      <div className="mt-12 p-5">
```

2020-08-01 17:17 UTC, insuusvenerati commented on zappnode-front/src/routes/Dashboard.js
>        <div className="mt-12">
```suggestion
      <div className="mt-12 p-5">
```

2020-08-01 17:17 UTC, insuusvenerati commented on zappnode-front/src/routes/Dashboard.js
> +      <div>
```suggestion
      <div className="mt-6 p-5">
```

2020-08-02 16:08 UTC, insuusvenerati approved these changes

2020-08-02 16:09 UTC, insuusvenerati approved these changes

2020-08-02 16:10 UTC, insuusvenerati approved these changes

2020-08-02 17:32 UTC, binismail approved these changes
looks nice!! kudos

2020-08-02 18:40 UTC, insuusvenerati commented
Trying to approve this but Github is being uncooperative. Sorry for the delay

2020-08-02 18:55 UTC, binismail commented
> Trying to approve this but Github is being uncooperative. Sorry for the delay

you know, unless you are assigned you can't approve

2020-08-03 10:39 UTC, aorelhas approved these changes
Since the people from the frontend give good feedback, I'll merge.

2020-08-03 10:40 UTC, merged